services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8000:8000" # PHP dev server
        volumes:
            - .:/app
        depends_on:
            - db
        network_mode: host # Use host network

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
